timezone: Europe/Berlin
markdown: kramdown
exclude: ['bower_components', 'Gemfile.lock', 'Gemfile', 'CNAME', 'README.md', 'Rakefile']
highlighter: true
encoding: UTF-8
permalink: date #?

defaults:
  -
    scope:
      path: ""
      type: "page"
    values:
      layout: "page"
      author: "James Duncan Davidson"
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"

# defaults:
#   - scope:
#       path: ""
#     values:
#       layout: "default"
#       author: "James Duncan Davidson"
#   - scope:
#       type: "post"
#     values:
#       layout: "post"
# kramdown:
#   input: GFM
