timezone: Europe/Berlin
markdown: kramdown
exclude: ['bower_components', 'Gemfile.lock', 'Gemfile', 'README.md', 'Rakefile', 's3_website.yml', 'config.ru']
highlighter: true
encoding: UTF-8
permalink: date
relative_permalinks: false
permalink: pretty
defaults:
  -
    scope:
      path: ""
      type: "page"
    values:
      layout: "page"
      author: "James Duncan Davidson"
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
